packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.9.0
  '@orpc/openapi': ^1.9.0
  '@orpc/server': ^1.9.0
  '@orpc/zod': ^1.9.0
  '@prisma/client': ^6.15.0
  better-auth: ^1.3.13
  dotenv: ^17.2.3
  next: 15.5.4
  tsdown: ^0.15.5
  zod: 4.1.12
