packages:
  - apps/*
  - packages/*
catalog:
  next: 15.5.4
  zod: ^4.0.2
  "@orpc/server": ^1.9.0
  "@orpc/client": ^1.9.0
  "@orpc/openapi": ^1.9.0
  "@orpc/zod": ^1.9.0
  "@prisma/client": ^6.15.0
  better-auth: ^1.3.13
  dotenv: ^17.2.2
  tsdown: ^0.15.5
